name: Build and Deploy AWS Unified Firehose

on:
  pull_request:
    branches:
      - test_hrai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_E2E_TEST_ROLE }}
          aws-region: us-east-2

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Update Instrumentation Version
        run: |
          version=$(grep 'instrumentation_version' version.yaml | cut -d ' ' -f2)
          echo "Version found: $version"
          sed -i '' "s/\"instrumentation.version\", \"AttributeValue\": \".*\"/\"instrumentation.version\", \"AttributeValue\": \"$version\"/" firehose-template.yaml
          echo "updated firehose template"
          cat firehose-template.yaml

      - name: Build SAM Application
        run: sam build --template-file firehose-template.yaml --region us-east-2

      - name: Package SAM Application
        run: sam package --s3-bucket unified-lambda-cft-demo --output-template-file firehose-template.yaml --region us-east-2

      - name: Upload CloudFormation Template to S3
        run: aws s3 cp firehose-template.yaml s3://unified-lambda-cft-demo/firehose-template.yaml